In [15]:
import pandas as pd


# CGMData_df = pd.read_csv('CGMData.csv', parse_dates=[['Date', 'Time']],index_col='Date_Time', low_memory=False)
# InsulinData_df = pd.read_csv('InsulinData.csv', parse_dates=[['Date', 'Time']], index_col='Date_Time', low_memory=False)

CGMData_df = pd.read_csv('CGMData.csv', parse_dates=[['Date', 'Time']], low_memory=False)
InsulinData_df = pd.read_csv('InsulinData.csv', parse_dates=[['Date', 'Time']], low_memory=False)

# # Reverse dataframe to straight the date time order
# CGMData_df = CGMData_df.iloc[::-1]
# InsulinData_df = InsulinData_df.iloc[::-1]

# Find auto mode start date
filt = InsulinData_df['Alarm'] =='AUTO MODE ACTIVE PLGM OFF'
AutoModeStartDate = InsulinData_df.loc[filt]['Date_Time'].iloc[-1]
# AutoModeStartDate = AutoModeStartDate.date()

In [16]:
AutoModeStartDate

Timestamp('2017-08-09 08:07:13')

In [17]:
# Split CGMData to Auto mode and Manual Mode
# CGM_Manual_df = CGMData_df.loc[CGMData_df.index < AutoModeStartDate][['Sensor Glucose (mg/dL)', 'ISIG Value']]
# CGM_Auto_df = CGMData_df.loc[CGMData_df.index >= AutoModeStartDate][['Sensor Glucose (mg/dL)', 'ISIG Value']]

CGM_Manual_df = CGMData_df.loc[CGMData_df['Date_Time'] < AutoModeStartDate][['Date_Time','Sensor Glucose (mg/dL)']]
CGM_Auto_df = CGMData_df.loc[CGMData_df['Date_Time'] >= AutoModeStartDate][['Date_Time','Sensor Glucose (mg/dL)']]

In [4]:
CGM_Manual_df_grp = CGM_Manual_df.groupby(CGM_Manual_df['Date_Time'].dt.date)
CGM_Auto_df_grp = CGM_Auto_df.groupby(CGM_Auto_df['Date_Time'].dt.date)

In [5]:
# CGM_Manual_df_grp.size()

In [6]:
# CGM_Auto_df.reset_index(inplace=True)
# CGM_Manual_df.reset_index(inplace=True)

# CGM_Auto_df.groupby(CGM_Auto_df['Date_Time'].dt.date)

In [7]:
# # Remove Date_Time index 
# CGM_Auto_df.reset_index(inplace=True)
# CGM_Manual_df.reset_index(inplace=True)

# # Remove missing data from 'Sensor Glucose (mg/dL)' column
# CGM_Auto_df = CGM_Auto_df[CGM_Auto_df['Sensor Glucose (mg/dL)'].notna()]
# CGM_Manual_df = CGM_Manual_df[CGM_Manual_df['Sensor Glucose (mg/dL)'].notna()]

In [8]:
# # Group data by date
# CGM_Auto_df_grp_date = CGM_Auto_df.groupby(CGM_Auto_df['Date_Time'].dt.date)
# CGM_Manual_df_grp_date = CGM_Manual_df.groupby(CGM_Manual_df['Date_Time'].dt.date)

# Remove daily data count less than 80% and greater than 288
wholeday_Auto_df = CGM_Auto_df_grp.filter(lambda x: (x['Sensor Glucose (mg/dL)'].count()>=230) & (x['Sensor Glucose (mg/dL)'].count()<=288))
wholeday_Manual_df = CGM_Manual_df_grp.filter(lambda x: (x['Sensor Glucose (mg/dL)'].count()>=230) & (x['Sensor Glucose (mg/dL)'].count()<=288))

wholeday_Auto_df = wholeday_Auto_df[wholeday_Auto_df['Sensor Glucose (mg/dL)'].notna()]
wholeday_Manual_df = wholeday_Manual_df[wholeday_Manual_df['Sensor Glucose (mg/dL)'].notna()]

wholeday_Auto_df_grp = wholeday_Auto_df.groupby(wholeday_Auto_df['Date_Time'].dt.date)
wholeday_Manual_df_grp = wholeday_Manual_df.groupby(wholeday_Manual_df['Date_Time'].dt.date)

totalAutoModeDays = wholeday_Auto_df_grp.count().shape[0]
totalManualModeDays = wholeday_Manual_df_grp.count().shape[0]

In [9]:
wholeday_Auto_PercentSum = [0, 0, 0, 0, 0, 0] 
wholeday_Manual_PercentSum = [0, 0, 0, 0, 0, 0]
overnight_Auto_PercentSum = [0, 0, 0, 0, 0, 0] 
overnight_Manual_PercentSum = [0, 0, 0, 0, 0, 0] 
day_Auto_PercentSum = [0, 0, 0, 0, 0, 0]
day_Manual_PercentSum = [0, 0, 0, 0, 0, 0]

for name, group in wholeday_Auto_df_grp:

    wholeday_Auto_PercentSum[0] += (group[group['Sensor Glucose (mg/dL)']>180].count()[1])*100/288
    wholeday_Auto_PercentSum[1] += (group[group['Sensor Glucose (mg/dL)']>250].count()[1])*100/288
    wholeday_Auto_PercentSum[2] += (group[(group['Sensor Glucose (mg/dL)']>=70) & (group['Sensor Glucose (mg/dL)']<=180)].count()[1])*100/288
    wholeday_Auto_PercentSum[3] += (group[(group['Sensor Glucose (mg/dL)']>=70) & (group['Sensor Glucose (mg/dL)']<=150)].count()[1])*100/288
    wholeday_Auto_PercentSum[4] += (group[group['Sensor Glucose (mg/dL)']<70].count()[1])*100/288
    wholeday_Auto_PercentSum[5] += (group[group['Sensor Glucose (mg/dL)']<54].count()[1])*100/288
                                          
    overnight_Auto_df = group.loc[(group['Date_Time'].dt.time>=pd.to_datetime('00:00:00').time()) & (group['Date_Time'].dt.time<pd.to_datetime('06:00:00').time())]
    overnight_Auto_PercentSum[0] += (overnight_Auto_df[overnight_Auto_df['Sensor Glucose (mg/dL)']>180].count()[1])*100/288
    overnight_Auto_PercentSum[1] += (overnight_Auto_df[overnight_Auto_df['Sensor Glucose (mg/dL)']>250].count()[1])*100/288
    overnight_Auto_PercentSum[2] += (overnight_Auto_df[(overnight_Auto_df['Sensor Glucose (mg/dL)']>=70) & (overnight_Auto_df['Sensor Glucose (mg/dL)']<=180)].count()[1])*100/288
    overnight_Auto_PercentSum[3] += (overnight_Auto_df[(overnight_Auto_df['Sensor Glucose (mg/dL)']>=70) & (overnight_Auto_df['Sensor Glucose (mg/dL)']<=150)].count()[1])*100/288
    overnight_Auto_PercentSum[4] += (overnight_Auto_df[overnight_Auto_df['Sensor Glucose (mg/dL)']<70].count()[1])*100/288
    overnight_Auto_PercentSum[5] += (overnight_Auto_df[overnight_Auto_df['Sensor Glucose (mg/dL)']<54].count()[1])*100/288
    
    day_Auto_df = group.loc[(group['Date_Time'].dt.time>=pd.to_datetime('06:00:00').time()) & (group['Date_Time'].dt.time<pd.to_datetime('23:59:59').time())]
    day_Auto_PercentSum[0] += (day_Auto_df[day_Auto_df['Sensor Glucose (mg/dL)']>180].count()[1])*100/288
    day_Auto_PercentSum[1] += (day_Auto_df[day_Auto_df['Sensor Glucose (mg/dL)']>250].count()[1])*100/288
    day_Auto_PercentSum[2] += (day_Auto_df[(day_Auto_df['Sensor Glucose (mg/dL)']>=70) & (day_Auto_df['Sensor Glucose (mg/dL)']<=180)].count()[1])*100/288
    day_Auto_PercentSum[3] += (day_Auto_df[(day_Auto_df['Sensor Glucose (mg/dL)']>=70) & (day_Auto_df['Sensor Glucose (mg/dL)']<=150)].count()[1])*100/288
    day_Auto_PercentSum[4] += (day_Auto_df[day_Auto_df['Sensor Glucose (mg/dL)']<70].count()[1])*100/288
    day_Auto_PercentSum[5] += (day_Auto_df[day_Auto_df['Sensor Glucose (mg/dL)']<54].count()[1])*100/288
    
    
for name, group in wholeday_Manual_df_grp:

    wholeday_Manual_PercentSum[0] += (group[group['Sensor Glucose (mg/dL)']>180].count()[1])*100/288
    wholeday_Manual_PercentSum[1] += (group[group['Sensor Glucose (mg/dL)']>250].count()[1])*100/288
    wholeday_Manual_PercentSum[2] += (group[(group['Sensor Glucose (mg/dL)']>=70) & (group['Sensor Glucose (mg/dL)']<=180)].count()[1])*100/288
    wholeday_Manual_PercentSum[3] += (group[(group['Sensor Glucose (mg/dL)']>=70) & (group['Sensor Glucose (mg/dL)']<=150)].count()[1])*100/288
    wholeday_Manual_PercentSum[4] += (group[group['Sensor Glucose (mg/dL)']<70].count()[1])*100/288
    wholeday_Manual_PercentSum[5] += (group[group['Sensor Glucose (mg/dL)']<54].count()[1])*100/288
                                          
    overnight_Manual_df = group.loc[(group['Date_Time'].dt.time>=pd.to_datetime('00:00:00').time()) & (group['Date_Time'].dt.time<pd.to_datetime('06:00:00').time())]
    overnight_Manual_PercentSum[0] += (overnight_Manual_df[overnight_Manual_df['Sensor Glucose (mg/dL)']>180].count()[1])*100/288
    overnight_Manual_PercentSum[1] += (overnight_Manual_df[overnight_Manual_df['Sensor Glucose (mg/dL)']>250].count()[1])*100/288
    overnight_Manual_PercentSum[2] += (overnight_Manual_df[(overnight_Manual_df['Sensor Glucose (mg/dL)']>=70) & (overnight_Manual_df['Sensor Glucose (mg/dL)']<=180)].count()[1])*100/288
    overnight_Manual_PercentSum[3] += (overnight_Manual_df[(overnight_Manual_df['Sensor Glucose (mg/dL)']>=70) & (overnight_Manual_df['Sensor Glucose (mg/dL)']<=150)].count()[1])*100/288
    overnight_Manual_PercentSum[4] += (overnight_Manual_df[overnight_Manual_df['Sensor Glucose (mg/dL)']<70].count()[1])*100/288
    overnight_Manual_PercentSum[5] += (overnight_Manual_df[overnight_Manual_df['Sensor Glucose (mg/dL)']<54].count()[1])*100/288
    
    day_Manual_df = group.loc[(group['Date_Time'].dt.time>=pd.to_datetime('06:00:00').time()) & (group['Date_Time'].dt.time<pd.to_datetime('23:59:59').time())]
    day_Manual_PercentSum[0] += (day_Manual_df[day_Manual_df['Sensor Glucose (mg/dL)']>180].count()[1])*100/288
    day_Manual_PercentSum[1] += (day_Manual_df[day_Manual_df['Sensor Glucose (mg/dL)']>250].count()[1])*100/288
    day_Manual_PercentSum[2] += (day_Manual_df[(day_Manual_df['Sensor Glucose (mg/dL)']>=70) & (day_Manual_df['Sensor Glucose (mg/dL)']<=180)].count()[1])*100/288
    day_Manual_PercentSum[3] += (day_Manual_df[(day_Manual_df['Sensor Glucose (mg/dL)']>=70) & (day_Manual_df['Sensor Glucose (mg/dL)']<=150)].count()[1])*100/288
    day_Manual_PercentSum[4] += (day_Manual_df[day_Manual_df['Sensor Glucose (mg/dL)']<70].count()[1])*100/288
    day_Manual_PercentSum[5] += (day_Manual_df[day_Manual_df['Sensor Glucose (mg/dL)']<54].count()[1])*100/288
    
result = {
    
'1':[overnight_Manual_PercentSum[0]/totalManualModeDays,overnight_Auto_PercentSum[0]/totalAutoModeDays],
    
'2':[overnight_Manual_PercentSum[1]/totalManualModeDays,overnight_Auto_PercentSum[1]/totalAutoModeDays],
    
'3':[overnight_Manual_PercentSum[2]/totalManualModeDays,overnight_Auto_PercentSum[2]/totalAutoModeDays],

'4':[overnight_Manual_PercentSum[3]/totalManualModeDays,overnight_Auto_PercentSum[3]/totalAutoModeDays],
    
'5':[overnight_Manual_PercentSum[4]/totalManualModeDays,overnight_Auto_PercentSum[4]/totalAutoModeDays],

'6':[overnight_Manual_PercentSum[5]/totalManualModeDays,overnight_Auto_PercentSum[5]/totalAutoModeDays],

    
'7':[day_Manual_PercentSum[0]/totalManualModeDays,day_Auto_PercentSum[0]/totalAutoModeDays],
    
'8':[day_Manual_PercentSum[1]/totalManualModeDays,day_Auto_PercentSum[1]/totalAutoModeDays],
    
'9':[day_Manual_PercentSum[2]/totalManualModeDays,day_Auto_PercentSum[2]/totalAutoModeDays],

'10':[day_Manual_PercentSum[3]/totalManualModeDays,day_Auto_PercentSum[3]/totalAutoModeDays],

'11':[day_Manual_PercentSum[4]/totalManualModeDays,day_Auto_PercentSum[4]/totalAutoModeDays],

'12':[day_Manual_PercentSum[5]/totalManualModeDays,day_Auto_PercentSum[5]/totalAutoModeDays],


'13':[wholeday_Manual_PercentSum[0]/totalManualModeDays,wholeday_Auto_PercentSum[0]/totalAutoModeDays],

'14':[wholeday_Manual_PercentSum[1]/totalManualModeDays,wholeday_Auto_PercentSum[1]/totalAutoModeDays],
   
'15':[wholeday_Manual_PercentSum[2]/totalManualModeDays,wholeday_Auto_PercentSum[2]/totalAutoModeDays],

'16':[wholeday_Manual_PercentSum[3]/totalManualModeDays,wholeday_Auto_PercentSum[3]/totalAutoModeDays],

'17':[wholeday_Manual_PercentSum[4]/totalManualModeDays,wholeday_Auto_PercentSum[4]/totalAutoModeDays],

'18':[wholeday_Manual_PercentSum[5]/totalManualModeDays,wholeday_Auto_PercentSum[5]/totalAutoModeDays],
 
}

result_df = pd.DataFrame(result, index =['Manual Mode', 'Auto Mode'])
result_df
# result_df.to_csv('Results.csv', index=False, header=False)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
Manual Mode,4.108796,0.839120,18.865741,14.236111,0.839120,0.000000,26.765046,9.490741,41.608796,32.436343,3.761574,1.707176,30.873843,10.329861,60.474537,46.672454,4.600694,1.707176
Auto Mode,2.816358,0.419844,20.613199,17.919390,0.612745,0.154321,20.840142,5.024510,47.483206,35.487019,3.560730,1.080247,23.656500,5.444354,68.096405,53.406409,4.173475,1.234568

In [10]:
wholeday_Manual_df['Sensor Glucose (mg/dL)'].unique()

array([239., 242., 246., 250., 254., 255., 258., 260., 263., 269., 275.,
       281., 287., 279., 270., 267., 262., 257., 252., 248., 243., 237.,
       234., 232., 233., 241., 236., 230., 224., 221., 219., 223., 158.,
       151., 149., 141., 143., 139., 140., 135., 132., 126., 124., 127.,
       130., 131., 133., 129., 138., 144., 145., 147., 146., 148., 150.,
       155., 163., 162., 153., 159., 164., 168., 169., 170., 171., 173.,
       172., 175., 178., 179., 183., 185., 182., 176., 193., 198., 203.,
       225., 231., 235., 245., 244., 240., 249., 251., 261., 278., 259.,
       216., 210., 195., 194., 197., 202., 208., 214., 227., 228., 238.,
       247., 253., 266., 268., 264., 256., 188., 123., 116., 106., 107.,
       114., 110., 105., 100.,  98.,  96.,  95.,  94.,  93.,  91.,  90.,
        92.,  99., 101., 103., 108., 109., 112., 117., 120., 125., 128.,
       152., 157., 161., 165., 167., 181., 184., 186., 187., 180., 174.,
       191., 192., 271., 284., 297., 306., 311., 315., 317., 316., 318.,
       309., 308., 301., 294., 291., 226., 220., 215., 211., 199., 142.,
       121.,  86.,  77.,  67.,  58.,  53.,  50.,  52.,  55.,  61.,  64.,
        65.,  66.,  70.,  74.,  79.,  85., 113., 122., 166., 209., 213.,
       217., 212., 206., 280., 290., 265., 160., 119., 154., 156., 115.,
       104.,  87., 102., 118., 137., 136., 134., 190., 196., 222., 229.,
       289., 298., 312., 319., 304., 300., 295., 299., 201.,  88.,  89.,
        97., 111.,  82.,  80.,  81.,  83.,  84.,  72.,  62.,  60.,  63.,
        57., 200., 204., 283., 288., 292., 296., 307., 272., 218., 282.,
       305., 329., 335., 341., 350., 360., 369., 374., 376., 380., 365.,
       358., 361., 367., 377., 373., 347., 331., 303., 205., 207., 277.,
       313., 320., 323., 325., 326., 328., 327., 286., 274.,  71.,  47.,
        44.,  45.,  68., 273., 302., 293., 276., 177.,  56.,  76.,  75.,
        78.,  48.,  49.,  51.,  73., 189.,  54.,  69.,  59.,  46.,  40.,
        41.,  43., 334., 342., 346., 349., 357., 366., 368., 362., 339.,
       324., 321.])

In [11]:
wholeday_Auto_df['Sensor Glucose (mg/dL)'].unique()

array([250., 245., 247., 243., 227., 213., 205., 182., 175., 170., 166.,
       164., 165., 158., 153., 161., 177., 194., 200., 201., 189., 162.,
       173., 176., 169., 167., 168., 180., 178., 171., 160., 145., 138.,
       132., 120., 127., 129., 123., 104., 100., 107., 106., 128., 137.,
       147., 142., 203., 206., 208., 215., 212., 196., 190., 184., 186.,
       207., 220., 198., 211., 217., 216., 221., 219., 209., 202., 197.,
       191., 185., 174., 136., 135., 148., 144., 141., 133., 126., 110.,
        74.,  62.,  58.,  57.,  60.,  61.,  63.,  65.,  69.,  70.,  67.,
        66.,  72.,  75.,  84.,  90.,  92.,  86.,  80., 108., 113., 115.,
       114., 111., 116., 150., 140., 131.,  95.,  79.,  71.,  76.,  81.,
        87.,  89.,  94.,  96.,  99., 103., 105.,  97.,  93., 109., 101.,
        98.,  91.,  77.,  73.,  68.,  59.,  78.,  83., 155., 163., 146.,
       121.,  82.,  64.,  56., 118., 179., 195., 218., 229., 236., 241.,
       244., 239., 246., 242., 232., 226., 234., 249., 252., 172., 154.,
       151., 156., 159., 149., 157., 124., 119., 117., 122., 102.,  88.,
       130., 139., 143., 152., 204., 193., 192., 134., 125., 183., 222.,
       228., 230., 223., 224., 225., 257., 266., 278., 291., 296., 294.,
       282., 272., 254.,  47.,  40.,  43.,  55., 258., 280., 303., 324.,
       347., 356., 363., 360., 365., 366., 370., 369., 376., 377., 379.,
       383., 386., 381., 380., 367., 353., 349., 348., 346., 344., 338.,
       332., 333., 330., 328., 317., 309., 293., 290., 260., 231., 237.,
        85., 214., 112.,  54., 240., 255., 270., 274., 263., 276., 285.,
       301., 306., 308., 323., 339., 343., 340., 345., 375., 378., 374.,
       371., 372., 362., 335., 312., 284., 275.,  52.,  42.,  51., 181.,
       188., 238., 256., 262., 264., 269., 299., 329., 336., 331., 281.,
       268., 187.,  50.,  48.,  53., 199., 261., 210., 259., 271., 251.,
       248., 267., 277.,  49., 233., 235., 287., 297., 305., 313., 298.,
       295., 289., 253., 265., 273., 283., 286., 300., 337., 321., 311.,
       318.,  46.,  44.,  45.,  41., 288., 279., 319., 326., 304., 292.,
       302., 314., 316., 320., 322., 310., 350., 358., 357., 351., 342.,
       327., 307., 355., 361., 341., 354., 352., 334., 400., 391., 368.,
       315., 359., 364., 382., 394., 392., 393., 390., 387., 373., 389.,
       395., 399., 398., 385., 325.])

In [12]:
wholeday_Auto_df_grp.count()

            Date_Time  Sensor Glucose (mg/dL)
Date_Time
2017-08-09        288                     288
2017-08-11        287                     287
2017-08-12        288                     288
2017-08-13        268                     268
2017-08-14        269                     269
...               ...                     ...
2018-02-07        277                     277
2018-02-08        282                     282
2018-02-09        285                     285
2018-02-10        285                     285
2018-02-11        234                     234

[153 rows x 2 columns]

In [13]:
wholeday_Manual_df_grp.count()

            Date_Time  Sensor Glucose (mg/dL)
Date_Time
2017-07-26        288                     288
2017-07-27        287                     287
2017-07-28        287                     287
2017-07-29        278                     278
2017-07-30        239                     239
2017-08-01        288                     288
2017-08-02        288                     288
2017-08-03        288                     288
2017-08-04        261                     261
2017-08-06        287                     287
2017-08-07        267                     267
2017-08-08        258                     258